#!/bin/bash

echo "Hello World"
mvn clean package
/home/acave/resin-pro-4.0.27/bin/resin.sh undeploy backbone_project-1.0-SNAPSHOT
/home/acave/resin-pro-4.0.27/bin/resin.sh deploy target/backbone_project-1.0-SNAPSHOT.war
/home/acave/resin-pro-4.0.27/bin/resin.sh deploy-list 
